version: "3"

services:
  db:
    platform: linux/x86_64 # M1 Macの場合必要
    image: mysql:5.7
    container_name: $DB_CONTAINER_NAME
    ports:
      - "${DB_CONTAINER_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  wordpress:
    depends_on:
      - db
    build:
      context: $WORDPRESS_IMAGE_BUILD_CONTEXT
      dockerfile: Dockerfile
    container_name: $WORDPRESS_CONTAINER_NAME
    ports:
      - "${WORDPRESS_CONTAINER_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./public_html:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini

  redis:
    image: redis:7.0.5
    container_name: $REDIS_CONTAINER_NAME
    ports:
      - "${REDIS_CONTAINER_PORT}:6379"
    volumes:
      - redis-data:/data

volumes:
  db_data:
  redis-data:
